machine:
  services:
    - docker

jobs:
  build:
    docker:
      - image:
        auth:
          username: circleci-registry-reader@echoparklabs.iam.gserviceaccount.com
          password: $GCR_PASSWORD

dependencies:
  override:
    - docker info
    - docker build --rm=false -t us.gcr.io/echoparklabs/geometry-api-java .
